# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: Free Trial(1905b060-3f48-4b00-8b11-7554c4fc2492)
  resourceGroup: resourcegroup-tfstate
  storageAccount: terraformtfstateskip
  container: tfstate
  tfstateFile: terraform.tfstate

steps:
- task: TerraformInstaller@0
  displayName: Install Terraform v0.14.0
  inputs:
    terraformVersion: '0.14.0'

- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Free Trial(1905b060-3f48-4b00-8b11-7554c4fc2492)'
    backendAzureRmResourceGroupName: '$(resourceGroup)'
    backendAzureRmStorageAccountName: '$(storageAccount)'
    backendAzureRmContainerName: '$(container)'
    backendAzureRmKey: '$(tfstateFile)'
    allowTelemetryCollection: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      az login 
      
      ACCOUNT_JSON=$(az account show -o json)
      
      TENANT_ID=$(echo $ACCOUNT_JSON | jq -r '.tenantId')
      SUBSCRIPTION_ID=$(echo $ACCOUNT_JSON | jq -r '.id')
      
      echo $TENANT_ID
      echo $SUBSCRIPTION_ID