apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-api
  template:
    metadata:
      labels:
        app: simple-web-api
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: simple-web-api
        image: simplewebapiacr.azurecr.io/simplewebapiimage:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-api-svc
spec:
  selector:
    app: simple-web-api
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80

